driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.8
  - name: centos-7.2
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: add_test
    data_bags_path: "test/fixtures/data_bags"
    encrypted_data_bag_secret_key_path: "test/fixtures/encrypted_data_bag_secret"
    run_list:
      - recipe[fake::aws_mock]
      - recipe[fake::add_test]
    attributes:
      aws_security:
        mocking: true
        encrypted_data_bag: aws_security

  - name: remove_test
    data_bags_path: "test/fixtures/data_bags"
    encrypted_data_bag_secret_key_path: "test/fixtures/encrypted_data_bag_secret"
    run_list:
      - recipe[fake::aws_mock]
      - recipe[fake::add_test]
      - recipe[fake::remove_test]
    attributes:
      aws_security:
        mocking: true
        encrypted_data_bag: aws_security
