---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.5

suites:
  - name: add_test
    data_bags_path: "test/integration/add_test/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/add_test/encrypted_data_bag_secret"
    run_list:
      - recipe[fake::add_test]
    attributes: {
      aws_security: {
      	encrypted_data_bag: "aws_security"
      }
    }
  - name: remove_test
    data_bags_path: "test/integration/remove_test/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/remove_test/encrypted_data_bag_secret"
    run_list:
      - recipe[fake::add_test]
      - recipe[fake::remove_test]
    attributes: {
      aws_security: {
        encrypted_data_bag: "aws_security"
      }
    }
